[package]
name = "superstruct"
version = "0.3.0"
edition = "2018"
description = "Proc-macro for quasi-subtyping"
license = "Apache-2.0"
repository = "https://github.com/sigp/superstruct"

[lib]
name = "superstruct"
proc-macro = true

[dependencies]
darling = "0.13.0"
itertools = "0.10.1"
proc-macro2 = "1.0.32"
quote = "1.0.10"
syn = "1.0.82"

[dev-dependencies]
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.72"
